nn_model_path: saved_models/nn_controller_test.eqx
nn_training:
  batch_size: 4
  cost_weights:
  - 10.0
  - 1.0
  - 0.01
  grad_clip: 1.0
  learning_rate: 0.001
  num_epochs: 5
  params_system:
  - 1.0
  - 0.1
  - 0.5
  - 9.81
  q_weights:
  - 0.1
  - 10.0
  - 10.0
  - 0.1
  - 0.1
  t_eval_points: 20
  t_span:
  - 0.0
  - 2.0
