model_xml: cart_pole_minimal.xml
sim_duration: 30.0
time_step: 0.01
nn_model_path: saved_models/nn_controller.eqx

nn_training:
  params_system: [1.0, 0.1, 0.5, 9.81]
  q_weights: [5.0, 20.0, 20.0, 1.0, 0.5]  # Moderate angle penalties
  cost_weights: [5.0, 1.0, 0.05]  # Emphasize energy, balanced state and control
  num_epochs: 500  # Longer training for better convergence
  batch_size: 128  # Larger batch improves gradient estimates
  t_span: [0.0, 6.0]  # Longer horizon to capture full swing-up
  t_eval_points: 60  # More evaluation points across the horizon
  learning_rate: 3e-4  # Conservative learning rate
  grad_clip: 1.0  # Relaxed clipping
  
  # New architecture parameters
  hidden_dims: [128, 128]  # Larger network for complex dynamics
  curriculum_learning: true  # Gradually increase difficulty
  curriculum_stages: 3  # Three-stage curriculum

linear_training:
  lr: 1e-4
  max_iters: 100
  tolerance: 1e-6
  w_init: [10.7477045, -0.00142533379, -95.3456802, 13.2174416, -27.8421364]

lqr:
  Q: [50.0, 100.0, 5.0, 20.0]
  R: 0.1
