# Cart-Pole Control System Configuration
# =====================================

# Simulation Settings
simulation:
  model_xml: cart_pole_minimal.xml
  duration: 30.0          # Simulation duration (seconds)
  time_step: 0.01         # Integration time step (seconds)
  
# Model Paths
models:
  nn_controller: saved_models/nn_controller.eqx

# Neural Network Training Configuration
nn_training:
  # System parameters: [mc, mp, l, g]
  system_params: [1.0, 0.1, 0.5, 9.81]
  
  # Cost function weights: [position, angle, velocity, angular_velocity, control]
  q_weights: [5.0, 20.0, 20.0, 1.0, 0.5]
  
  # Training hyperparameters
  num_epochs: 500
  batch_size: 128
  learning_rate: 3e-4
  grad_clip: 1.0
  
  # Time horizon settings
  t_span: [0.0, 6.0]      # Training horizon (seconds)
  t_eval_points: 60       # Number of evaluation points
  
  # Network architecture
  hidden_dims: [128, 128] # Hidden layer dimensions
  
  # Curriculum learning
  curriculum_learning: true
  curriculum_stages: 3

# Linear Controller Training
linear_training:
  learning_rate: 1e-4
  max_iterations: 100
  tolerance: 1e-6
  initial_weights: [10.75, -0.001, -95.35, 13.22, -27.84]

# LQR Controller Configuration
lqr:
  # State cost matrix Q: [position, angle, velocity, angular_velocity]
  Q: [20.0, 50.0, 5.0, 5.0]
  
  # Control cost matrix R
  R: 5.0
  
  # Performance targets
  min_damping: 0.8
  max_frequency: 3.0
  cost_scaling: 1.0